SYNTACTIC_DEVICES = {
    "anaphora": "Repetition of a word or phrase at the beginning of successive clauses or sentences",
    "epistrophe": "Repetition of a word or phrase at the end of successive clauses or sentences",
    "symploce": "Combination of anaphora and epistrophe; repetition of words or phrases at both the beginning and end of successive clauses or sentences",
    "parallelism": "Similarity of structure in a pair or series of related words, clauses or phrases",
    "enumeration": "Listing or detailing of words, phrases, or clauses, often for emphasis",
    "chiasmus": "Reversal of grammatical structures in successive clauses or phrases (AB-BA structure), often for insightful, epigrammatic effect (e.g., 'Ask not what your country can do for you, ask what you can do for your country', 'I own my SNS account, but my SNS account owns me', 'He who loves nature is loved by nature', etc.). This is **NOT antithesis or parallelism**, but about **SYNTACTIC structure**. Ensure that the examples are insightful and meaningful epigram, **NOT just simple rephrasing, passive-form or reordering of words.**",
    "antithesis": "Juxtaposition of contrasting ideas in balanced or parallel phrases or clauses",
    "climax": "Arrangement of words, phrases, or clauses in order of increasing importance",
    "anticlimax": "Arrangement of words, phrases, or clauses in order of decreasing importance, or a sudden shift from a serious to a trivial topic",
    "asyndeton": "Omission of conjunctions between coordinate phrases, clauses, or words",
    "polysyndeton": "Use of multiple conjunctions in close succession",
    "hypotaxis": "Use of subordination in syntax, where one clause is dependent on another, often to describe or modify the main clause",
    "parataxis": "Use of clauses or phrases placed side by side without the use of conjunctions or with minimal use of conjunctions, showing their relationship without subordinating elements",
    "ellipsis": "Omission or suppression of words or phrases that are implied but not stated, often to indicate brevity, pause, hesitation, or unfinished thought",
    "anastrophe": "Inversion of the usual order of words, often for emphasis or to maintain a rhyme scheme",
    "apposition": "Placing two different elements/expressions side by side, where one explains or modifies the other (e.g., 'John, my friend', 'New York, the city I live in', 'the king, a powerful ruler', etc.)",

    "isocolon": "Use of parallel structures of the same length in successive clauses",
    "hyperbaton": "Disruption or inversion of customary word order to produce a distinctive effect",
    "hypallage": "Transfer of epithet from the word it should logically belong to another word, often for rhetorical effect (e.g., 'a farmer walks the *tired* field' where 'tired' should logically belong to 'farmer', not 'field', 'a girl endured the *sleepless* night' where 'sleepless' should logically belong to 'a girl', not 'night', etc.)",
    "epanalepsis": "Repetition of the initial word or words of a clause or sentence at the end of the clause or sentence (e.g., 'The king is dead, long live the king', 'Nothing is worse than doing nothing', 'Never say never', etc.)",
    "anadiplosis": "Repetition of the last word of one clause at the beginning of the following clause",
    "synchysis": "Interlocked word order (often ABAB structure)",
    "hysteron_proteron": "Inversion of the natural sequence of events to place the more important event first, even though it occurs later in time",
    "mesodiplosis": "Repetition of the same word or phrase at the middle of successive clauses or sentences",
    "hypozeuxis": "Repetition of the same structure in the successive clauses or sentences, often related to enumeration, parallelism, climax, or antithesis.",
    "diacope": "Repetition of a word or phrase with one or more intervening words",
    "anacoluthon": "A sudden break in the grammatical sequence of a sentence",
    "epanorthosis": "Immediate rephrasing for intensification or correction",
    "parenthesis": "Insertion of a word, phrase, or whole sentence as an aside in the middle of another sentence, often marked by parentheses, commas, or dashes",
    "tricolon": "A series of three parallel words, phrases, or clauses",
}

SEMANTIC_DEVICES = {
    "simile": "Direct comparison using words that indicate comparison, such as 'like' or 'as'. To exemplify this rhetorical device, you **MUST** use 'like(～のような)' or 'as(まるで)' in the output sentences.",
    "metaphor": "Direct comparison **WITHOUT INDICATING COMPARISON**, such as 'like' or 'as'. To exemplify this rhetorical device, you **MUST NOT** include any words that indicate comparison, such as 'like(～のよう)' or 'as(まるで)' in the output sentences.",
    "symbolism": "Use of symbols to represent concepts or ideas (e.g., 'the dove' for peace, 'the rose' for love, 'the snake' for evil, etc.)",
    "allusion": "Reference to a well-known person, place, event, or work of art, without explicitly describing it (e.g., 'He's a real Romeo', 'She's a modern-day Da Vinci')",
    "apostrophe": "Direct address to an imaginary, dead, or absent person, or to an inanimate object or abstract concept (e.g., 'O, Death, where is thy sting?', 'O, Romeo, Romeo, wherefore art thou Romeo?', 'O, Time, suspend your flight!', etc.)",
    "personification": "describe inanimate objects, animals, or abstract concepts with human qualities or characteristics (e.g., 'the wind whispered', 'the sun smiled', 'the flowers danced', etc.)",
    "hypostatization": "describe humans or living beings with inanimate qualities or characteristics (e.g., 'motionless as a statue', 'killed like pawns', 'stone-hearted', etc.)", 
    "objectification": "describe concepts or abstract ideas as if they were physical objects (e.g., 'the truth is a hard pill to swallow', 'the words cut like a dagger', 'the future is a blank canvas', etc.)",
    "hyperbole": "Using exaggeration for emphasis or effect (e.g., 'I'm so hungry I could eat a horse', 'I've told you a million times', 'I'm dying of embarrassment', etc.)",
    "oxymoron": "Combination of contradictory or incongruous words for rhetorical effect (e.g., 'bittersweet', 'living dead', 'eternal moment', 'alone together', etc.). This is **NOT about simple antithesis or parallelism**, but about **COMBINING CONTRADICTORY WORDS**.",
    "paradox": "Using a statement that appears to be self-contradictory or illogical, but may reveal a deeper truth (e.g., 'less is more', 'I know that I know nothing', 'the beginning of the end', etc.)",
    "pleonasm": "Use of more words than necessary to convey meaning (e.g., 'free gift', 'burning fire', 'true fact', etc.)",
    "synecdoche": "Statement where a part of something is used to represent the whole or the whole is used to represent a part (e.g., 'bread' for the food, 'pen' for the writing, 'white-house' for the U.S. Government, etc.)",
    "metonymy": "Using a closely related term in substitution for the actual term (e.g., 'the crown' for the king, 'the White House' for the U.S. President, 'Hollywood' for the U.S. film industry, etc.)",
    "allegory": "Narrative or story with a hidden or symbolic meaning, often used to convey moral or political messages",
    "irony": "Use of words to convey a meaning that is the opposite of its literal meaning, often for humor or sarcasm (e.g., 'It's a beautiful day' when it's raining, 'I love waiting in line' when you hate waiting, etc.)",
    "litotes": "Understatement by using double negatives or, in other words, positive statement expressed by negating its opposite expressions or vise versa (e.g., 'not bad' for good, 'not unlike' for similar, 'not perfect' for bad, etc.)",
    "conceit": "Extended metaphor that compares two very dissimilar things in a surprising or clever way (e.g., 'the broken heart is a wounded deer', 'the love is a rose', 'the life is a journey', etc.)",
    "similitude": "Comparison of two things that are alike in some way, often to explain or clarify a concept (e.g., 'the mind is like a garden, because...', 'the life is like a river, because...', 'the love is like a flame, because...', etc.)",
    "kenning": "Metaphorical compound word or phrase used in place of a common noun (e.g., 'whale-road' for the sea, 'battle-sweat' for blood, etc.)",
    "periphrasis": "Using more words than necessary to describe something, often to avoid using a common or direct term (e.g., 'the city that never sleeps' for New York City, 'the king of the animals' for lion, 'the emperor of citizens' for the president, etc.)",
    "antonomasia": "Use of role, title, achievement, or characteristic in place of a proper name (e.g. 'the king of pop' for Michael Jackson, 'the father of modern physics' for Isaac Newton, etc.)",
    "euphemism": "Substitution of a mild, indirect, or vague term for a harsh, blunt, or offensive one (e.g., 'passed away' for died, 'let go' for fired, 'vertically challenged' for short, etc.)",
    "catachresis": "Intentional misuse or unusual use of a word for rhetorical effect (e.g., 'say dagger'=harsh insult, 'keep it green'=keep something environmentally friendly, 'this furniture is hurting'=this furniture is broken, etc.)",
    "dysphemism": "Substitution of a harsh, blunt, or offensive term for a mild, indirect, or vague one (e.g., 'hellhole' for prison, 'rambling nonsense' for speech, 'cancer stick' for cigarette, etc.)", 
    "meiosis": "Intentional understatement that implies something is lesser than it actually is, often for humor or emphasis (e.g., 'I'm just a little tired' for exhausted, 'It's just a scratch' for a deep cut, 'It's pinching a bit' for excruciating pain, etc.)",
}

PRAGMATIC_DEVICES = {
    "hypophora": "Asking a question to oneself and immediately answering it, often to introduce a topic or make a point.",
    "exclamation": "Forceful expression often used to convey strong emotion or command attention.",
    "sarcasm": "Saying one thing but meaning the opposite, often to mock or ridicule.",
    "humor": "Use of comedy or amusement to entertain or provoke laughter.",
    "concession": "Acknowledging a point or argument made by the other side, often to strengthen one's own argument.",
    "implicature": "Suggesting something without explicitly stating it, often to convey meaning indirectly (e.g., 'It's getting late' to imply 'we should leave soon', 'I'm thirsty' to imply 'can you get me a drink?', etc.)",
    "procatalepsis": "Anticipating and responding to an objection or argument before it is made.",
    "apophasis": "Mentioning something by saying not to mention it (e.g. 'I won't even bring up...', 'needless to say...', etc.), often to draw attention to it.",
    "aposiopesis": "Breaking off suddenly in speech, often to convey strong emotion or to create suspense (e.g., 'I swear, if you dare...', 'Oh my...', 'what the...', etc.)",
    "anapodoton": "Introducing (often to well-known) clause or phrase and leaving it incomplete, often to provoke curiosity or imagination (e.g., 'when in Rome...' for 'do as the Romans do', 'guess what...' for supposed to be a surprising fact, 'if only...' for supposed to be a wish, etc.)",
    "paraprosdokian": "Unexpected ending or twist in a sentence, often to create humor or surprise.",
    "ecphonesis": "An emotional, exclamatory phrase used to express strong feelings or to add emphasis.",
    "dialogismus": "Simulating a conversation or dialogue with oneself or others within the speech.",
    "epimone": "Persistent repetition of the same words or phrases to emphasize a point or idea.",
    "erotema": "Asking a rhetorical question to assert or deny something obliquely, not to elicit an answer.",
    "invective": "Abusive or highly critical language to denounce or criticize someone or something.",
    "bdelygmia": "Expressing strong hatred or disgust.",
    "epiplexis": "Asking questions to reproach or rebuke rather than to elicit answers.",
    "accismus": "Pretending to refuse or disinterest in something that actually desired, often to appear modest or polite (e.g., 'I'm not interested in buying that expensive car, even if I could afford it.', 'I don't want that prize, but will accept it if they insist.', etc.)",
    "anacoenosis": "Asking the audience for their opinion, often to involve (or manipulate) them in the argument.",
    "antanagoge": "Placing a positive point or benefit next to a fault or criticism to reduce the impact.",
    "epitrope": "Letting the opponent or audience to decide or conclude, often to imply the speaker's confidence, to force the opponent to admit a point.",
    "sententia": "Quoting a maxim or wise saying to apply a general truth to the situation.",
    "synchoresis": "Conceding a point to a disputant or opponent.",
    "pysma": "Asking a series of questions in rapid succession to overwhelm or confuse the audience."
}

LINGUISTIC_DEVICES = {
    "neologism": "Use of newly-coined or invented words or expressions",
    "derivation": "Use of a word from another word or base",
    "transliteration": "Transformation of a word from one language to another. (e.g., '東京' to 'TOKYO')",
    "synonym": "Combination of words with similar meanings to emphasize or clarify",
    "antonym": "Combination of words with opposite meanings to compare or contrast",
    "semantic_extension": "Expansion of words' meaning to include additional concepts",
    "archaism": "Use of old-fashioned or outdated words or linguistic forms. **References to historical events, figures, or concepts are not considered 'archaism' rhetorical devices, ensure the examples are archaic in linguistic form, not in content.**",
    "dialect": "Use of regional or social variation in language. This is not describing the dialect itself, but using dialectical expressions or words in the text.",
    "jargon": "Use of specialized terminology within a particular field or group",
    "colloquialism": "Use of informal words or phrases associated with casual conversation",
    "slang": "Use of very informal language or unconventional vocabulary, often associated with youth culture or subcultures",
    "loanword": "Use of a word from other language without translation",
    "calque": "Word-for-word translation of a word or phrase from other language, often employed for technical or legal impressions (e.g. '摩天楼' from 'sky-scraper', '借用語' from 'loan-word', etc.)",
    "portmanteau": "Combination of multiple words to create a new word with a blended meaning (e.g., 'brunch' from 'breakfast' and 'lunch', 'smog' from 'smoke' and 'fog', 'motel' from 'motor' and 'hotel', etc.)",
    "malapropism": "Use of a word that sounds similar to the intended word but has a different meaning, often to induce ignorance, humor, or confusion",
    "cliché": "Use of well-known, overused or unoriginal phrases or expressions",
}

SENSORY_DEVICES = {
    "visual_imagery": "Description utilizing sight or visual elements",
    "auditory_imagery": "Description utilizing sound or auditory elements",
    "olfactory_imagery": "Description utilizing smell or olfactory elements",
    "gustatory_imagery": "Description utilizing taste or gustatory elements",
    "tactile_imagery": "Description utilizing touch or tactile elements",
    "thermal_imagery": "Description utilizing temperature or thermal elements",
    "proprioceptive_imagery": "Description utilizing body position or movement elements",
    "equilibrial_imagery": "Description utilizing sense of **PHYSICAL** equilibrium, posture, or balance elements. **This is NOT about 'balance' in the sense of fairness or equality**, NOR metaphorical balance in writing or argumentation, but about **PHYSICAL SENCE OF BALANCE**. **NEVER OUTPUT metaphorical or abstract 'balance'!!!**",
    "chromatic_imagery": "Description utilizing color or chromatic elements",
    "luminance_imagery": "Description utilizing brightness/darkness or light/dark elements with wide range: from dazzling or blinding light to pitch-black or complete darkness",
    "atmospheric_imagery": "Description utilizing the sense of air-flow or atmosphere",
    "interoceptive_imagery": "Description utilizing internal bodily sensations related to physiological conditions",
    "pain_imagery": "Description utilizing pain or painful sensations",
    "temporal_imagery": "Description utilizing temporal-sense or time elements",
    "spatial_imagery": "Description utilizing spatial-sense or space elements",
    "shape_imagery": "Description utilizing the perception of shapes or forms",
    "synesthesia": "Description utilizing multiple senses or sensory blending",
}

LOGICAL_DEVICES = {
    "syllogism": "Form of deductive reasoning with two premises and a conclusion",
    "analogy": "Reasoning that if two things are similar in some respects, they are likely to be similar in others.",
    "induction": "Reasoning from specific cases to a general conclusion.",
    "deduction": "Reasoning from general principles to a specific conclusion.",
    "abduction": "Reasoning to the best explanation for a set of observations.",
    "reductio_ad_absurdum": "Disproving an argument by showing its absurd consequences.",
    "double_negation": "Proving a statement by denying its negation.",
    "contraposition": "Proving a statement by showing its contrapositive is true.",
    "conjunction": "Combining two or more statements to form a single statement.",
    "disjunction": "Presenting two or more alternatives, often with the implication that one is true.",
    "causal_reasoning": "Identifying cause-effect relationships between events.",
    "enthymeme": "Omission of a premise in an argument, often to make it more persuasive or conceal a weak point.",
    "logical_fallacies": "Reasoning that **intentionally lacks or distorts** logical coherence or consistency, often to be deceptive, misleading, or manipulative. Accidental mistakes in reasoning are not considered logical-fallacy-rhetorics, but intentional malpractices are. To exemplify this rhetorical device, you must **INTENTIONALLY make deceptive or misleading logical fallacies**.",
}

PSYCHOLOGICAL_DEVICES = {
    "ethos": "Argument/rhetoric appeals to ethics or credibility",
    "pathos": "Argument/rhetoric appeals to emotions or feelings",
    "eunoia": "Argument/rhetoric appeals to goodwill or kindness",
    "philia": "Argument/rhetoric appeals to friendship or camaraderie",
    "charis": "Argument/rhetoric appeals to grace or generosity",
    "communitas": "Argument/rhetoric appeals to community or shared experience",
    "arete": "Argument/rhetoric appeals to excellence or virtue",
    "phronesis": "Argument/rhetoric appeals to practical wisdom or common sense",
    "catharsis": "Purging or cleansing of emotions through art or literature",
    "pneuma": "Argument/rhetoric appeals to spirit or spiritual beliefs",
    "mythos": "Argument/rhetoric appeals to cultural beliefs or traditional stories",
    "aporia": "Argument/rhetoric appeals to doubt or uncertainty to provoke thought",
    "metanoia": "Argument/rhetoric appeals to change or transformation of mind or heart",
    "nostalgia": "Argument/rhetoric appeals to sentimental longing for the past",
    "nemesis": "Argument/rhetoric appeals to divine retribution or punishment",
    "kairos": "Argument/rhetoric appeals to the timeliness or opportune moment",
    "sympatheia": "Argument/rhetoric appeals to shared emotions or mutual understanding",
    "thymos": "Argument/rhetoric appeals to spiritedness or emotional intensity",
    "elpis": "Argument/rhetoric appeals to hope or positive expectations",
    "agape": "Argument/rhetoric appeals to selfless love or charity",
    "phobos": "Argument/rhetoric appeals to fear or anxiety to provoke a reaction",
    "eikos": "Argument/rhetoric appeals to probability or what is likely to happen, creating a sense of inevitability",
    "ataraxia": "Argument/rhetoric appeals to tranquility or peace of mind",
    "neikos": "Argument/rhetoric appeals to conflict or discord to create tension or drama",
    "epithumia": "Argument/rhetoric appeals to desire or passion to evoke strong emotions",
}

# Rhetorical devices that cannot be effectively generated by LLM
# These devices require a deep understanding of the context, culture, or human experience, which are beyond the capabilities of current LLMs.
DEVICES_CANNOT_BE_GENERATED = {
    # "zeugma": "Use of a word to modify or govern two or more words with different meanings, often to create a pun or clever effect (e.g., 'He stole both her car and her heart', 'She broke his car and his heart', 'He lost his coat and his temper', etc.). This is **NOT about simple parallelism**, but about **MODIFYING MULTIPLE WORDS WITH A SINGLE WORD**. Ensure that the examples are insightful and meaningful, **NOT just simple parallelism**.",
    # "pun": "(paronomasia) Play on words; use of words alike in sound but different in meaning. (e.g., 'A bicycle can't stand on its own because it is **two-tired**.', 'The best way to stop a **charging** bull is to take away his **credit card**.')",
    # "anthimeria": "Substitution of one part-of-speech (noun, verb, adjective, etc.) for another. (e.g., 'Google it'=using noun as verb, 'Good cry is therapeutic'=using verb as noun, etc.)",
    # "palindrome": "use of words or phrases that read the same forwards and backwards (e.g., 'level', 'radar', 'madam', etc.)",
    # "spoonerism": "intentional swapping of letters (both vowels and consonants) in two or more words, often for humorous effect (e.g., 'You have hissed all my mystery lectures' for 'You have missed all my history lectures', 'A blushing crow' for 'A crushing blow', etc.). To exemplify this rhetorical device, you must **INTENTIONALLY make mistakes** in the output sentences.",
}

ALL_RHETORICAL_DEVICES = {**SYNTACTIC_DEVICES, **SEMANTIC_DEVICES, **PRAGMATIC_DEVICES, **LINGUISTIC_DEVICES, **SENSORY_DEVICES, **LOGICAL_DEVICES, **PSYCHOLOGICAL_DEVICES}